// DARK THEME
export const DARK_COLOR = '#1f1f1f'
// LIGHT THEME
export const LIGHT_COLOR = 'rgb(255, 255, 255)'
// DEFAULT GRADIENT COLOR ONE
export const DEFAULT_COLOR_ONE = '#81FFEF'
// DEFAULT GRADIENT COLOR TWO
export const DEFAULT_COLOR_TWO = '#F067B4'
// GRADIENT CONTAINER WIDTH
export const GRADIENT_CONTAINER_WIDTH = '170px'
// GRADIENT CONTAINER HEIGHT
export const GRADIENT_CONTAINER_HEIGHT = '295px'
export const DEFAULT_SWATCHES = [
  '#5a80b4',
  '#40e0d0',
  '#088da5',
  '#f6546a',
  '#cac8a0',
  '#0079cf',
  '#ffa6ca',
  '#03ec13',
  '#3999dc',
  '#e1c9ec',
  '#2f9d66',
  '#daa520'
]
// DEFAULT COLOR INPUT
export const DEFAULT_COLOR = '#088da5'
// REQUIRED FOR GENERATING SWATCHES FROM AN IMAGE
export const MAX_COLORS = 64
// WIDTH OF THE COLOR PICKER
export const COLOR_CONTAINER_WIDTH = '228px'
// HEIGHT OF THE COLOR PICKER
export const COLOR_CONTAINER_HEIGHT = '295px'
// DEFAULT COLOR STOP POSITION
export const DEFAULT_COLOR_STOP = 0.2
// WIDTH OF SCHEME PICKER
export const SCHEME_CONTAINER_WIDTH = '200px'
// HEIGHT OF SCHEME PICKER
export const SCHEME_CONTAINER_HEIGHT = '225px'
